# Build stage
FROM maven:3.9.9-amazoncorretto-21-alpine AS build

# Thiết lập thư mục làm việc cho giai đoạn build
WORKDIR /app

# Copy file pom.xml và thư mục src
COPY ../api-gateway/pom.xml .
COPY ../api-gateway/src ./src

# Build ứng dụng
RUN mvn package -DskipTests

# Run stage
FROM amazoncorretto:21.0.5-al2023

# Thiết lập thư mục làm việc cho container
WORKDIR /app

# Copy file JAR từ build stage
COPY --from=build /app/target/*.jar app.jar

# Mở cổng 8080
EXPOSE 8080

# Lệnh để khởi chạy ứng dụng
ENTRYPOINT ["java", "-jar", "app.jar"]
