server:
  port: 8080
  servlet:
    context-path: /auth

email: hoanghuutuyen06022004@gmail.com

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/auth-micro?useSSL=false"
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: notify-email-welcome
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: com.shop.event,com.shop.event
#  security:
#    oauth2:
#      client:
#        registration:
jwt:
  signerKey: "8d01f3c2a52fa0af4a3619ab447510da38909d2e9a7386de1005ebd280d4b8f2a24ef2bb6c99a28f5386c07c01da3ff3c5f65490077d209a25a50485b3543020"

app:
  service:
    profile:
      url: "http://localhost:8081/profile"
      name: "profile-service"
    notification:
      url: "http://localhost:8082/notify"
      name: "notification-service"
