server:
  port: 8082
  servlet:
    context-path: /notify
notification:
  email:
    brevo-url: https://api.brevo.com
    brevo-apikey: "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"
    sender: "hoanghuutuyen060204@gmail.com"
    name: "HTShop"
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/notify-micro?useSSL=false"
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: notify-email-welcome-v1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.kafka.consumer.properties.spring.json.trusted.packages: com.shop.event
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer


