
server:
  port: 8888
app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/auth/**
          filters:
            - StripPrefix=2
        - id: notification_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/notify/**
          filters:
            - StripPrefix=2
        - id: product_service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/product/**
          filters:
            - StripPrefix=2



