server:
  port: 8085
  servlet:
    context-path: /bill
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bill-micro
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
