server:
  port: 8084
  servlet:
    context-path: /product

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/product-micro?useSSL=false"
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
