server:
  port: 8081
  servlet:
    context-path: /inventory
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
app:
  service:
    product:
      name: "product-service"
      url: "http://localhost:8084/product"
